import type { EtapaProductivaRecord } from './types'
import { FACTORES_TECNICOS, FACTORES_ACTITUDINALES, nuevosFactores } from './types'

// Datos de ejemplo para revisar el diseño y el flujo mientras se define el
// formato definitivo. No hay backend todavía: esto solo vive en memoria.

function factoresLlenos(satisfactorios: number): { tecnicos: ReturnType<typeof nuevosFactores>; actitudinales: ReturnType<typeof nuevosFactores> } {
  const tecnicos = nuevosFactores(FACTORES_TECNICOS).map((f, i) => ({
    ...f, valoracion: i < satisfactorios ? 'SATISFACTORIO' as const : 'POR_MEJORAR' as const,
  }))
  const actitudinales = nuevosFactores(FACTORES_ACTITUDINALES).map((f, i) => ({
    ...f, valoracion: i < satisfactorios ? 'SATISFACTORIO' as const : 'POR_MEJORAR' as const,
  }))
  return { tecnicos, actitudinales }
}

export function mockRecords(): EtapaProductivaRecord[] {
  const f1 = factoresLlenos(8)
  const f2 = factoresLlenos(6)

  return [
    {
      id: 1,
      info: {
        regional: 'Distrito Capital',
        centroFormacion: 'Centro de Servicios Financieros',
        nivelFormativo: 'Tecnólogo',
        programaNombre: 'Análisis y Desarrollo de Software',
        programaCodigo: '228106',
        numeroFicha: '2758934',
        modalidadFormacion: 'PRESENCIAL',
        estrategiaFormativa: 'Contrato de aprendizaje',
        fechaFinEtapaLectiva: '2026-06-12',
        aprendiz: {
          nombreCompleto: 'Laura Camila Restrepo Gómez',
          tipoDocumento: 'CC',
          numeroIdentificacion: '1019456782',
          contactoTelefonico: '3114567890',
          direccion: 'Cra 45 # 12-30, Bogotá',
          correoPersonal: 'laura.restrepo@gmail.com',
          correoInstitucional: 'lrestrepog@soy.sena.edu.co',
          alternativaEtapaProductiva: 'Contrato de aprendizaje',
          fechaRegistroSofiaPlus: '2026-06-15',
        },
        instructorSeguimiento: {
          nombre: 'Jorge Andrés Peña Ruiz',
          contactoTelefonico: '3105551234',
          correoInstitucional: 'jpena@sena.edu.co',
        },
        enteCoformador: {
          nombreEmpresa: 'Soluciones Digitales SAS',
          direccion: 'Calle 100 # 19-61, Bogotá',
          nit: '900123456-7',
          correoElectronico: 'contacto@solucionesdigitales.co',
          nombreJefeInmediato: 'Marcela Duarte Silva',
          cargo: 'Líder de desarrollo',
          contactoTelefonico: '3201239988',
          nombreOtroContacto: '',
          telefonoInstitucional: '(601) 745 6600',
        },
        discapacidad: { aplica: false, nombreAsiste: '', tipoAsistencia: '', contactoTelefonico: '' },
      },
      momento1: {
        completado: true,
        fechaInicio: '2026-06-15',
        fechaFin: '2026-12-15',
        fechaAfiliacionArl: '2026-06-14',
        numeroPolizaArl: 'ARL-88213-2026',
        horario: 'Diurno · lunes a viernes 8:00am–5:00pm',
        enlaceGrabacion: '',
        competenciasDesarrollar: 'Desarrollar componentes de software de acuerdo con requerimientos del cliente y estándares de calidad.',
        resultadosAprendizaje: 'Aplica buenas prácticas de programación y control de versiones en un entorno productivo real.',
        actividadesDesarrollar: 'Desarrollo de módulos del sistema interno de facturación; pruebas unitarias; documentación técnica.',
        evidenciasAprendizaje: 'Repositorio de código, informes de avance quincenales, capturas de pruebas ejecutadas.',
        observacionesAdicionales: '',
        firmaAprendiz: true, firmaInstructor: true, firmaEnteCoformador: true,
        ciudad: 'Bogotá D.C.',
        fechaDiligenciamiento: '2026-06-13',
        modalidadDiligenciamiento: 'PRESENCIAL',
      },
      momento2: [
        {
          id: 1, fecha: '2026-06-15',
          modalidad: 'PRESENCIAL', enlaceGrabacion: '',
          factoresTecnicos: f1.tecnicos, factoresActitudinales: f1.actitudinales,
          observacionesInstructor: 'Buen manejo inicial del stack tecnológico de la empresa. Se recomienda reforzar documentación.',
          observacionesAprendiz: 'Me siento cómoda con el equipo y las herramientas.',
          observacionesEnteCoformador: 'Muy buena disposición y puntualidad.',
          firmaAprendiz: true, firmaInstructor: true, firmaEnteCoformador: true,
          ciudad: 'Bogotá D.C.', fechaDiligenciamiento: '2026-07-20',
        },
      ],
      momento3: {
        completado: false,
        fechaInicio: '2026-06-15', fechaFin: '', numeroVisitas: 1,
        modalidad: 'PRESENCIAL', enlaceGrabacion: '',
        factoresTecnicos: nuevosFactores(FACTORES_TECNICOS),
        factoresActitudinales: nuevosFactores(FACTORES_ACTITUDINALES),
        retroEnteProceso: '', retroEnteDesempeno: '',
        retroInstructorProceso: '', retroInstructorDesempeno: '',
        retroAprendizProceso: '', retroAprendizDesempeno: '',
        juicio: null,
        firmaAprendiz: false, firmaInstructor: false, firmaEnteCoformador: false,
        ciudad: '', fechaDiligenciamiento: '',
      },
      anexos: [],
    },
    {
      id: 2,
      info: {
        regional: 'Distrito Capital',
        centroFormacion: 'Centro de Servicios Financieros',
        nivelFormativo: 'Técnico',
        programaNombre: 'Contabilización de Operaciones Comerciales y Financieras',
        programaCodigo: '133112',
        numeroFicha: '2759112',
        modalidadFormacion: 'VIRTUAL',
        estrategiaFormativa: 'Pasantía',
        fechaFinEtapaLectiva: '2026-05-30',
        aprendiz: {
          nombreCompleto: 'Kevin Santiago Torres Marín',
          tipoDocumento: 'CC',
          numeroIdentificacion: '1024789456',
          contactoTelefonico: '3009874561',
          direccion: 'Calle 68 # 8-25, Bogotá',
          correoPersonal: 'kevin.torresm@hotmail.com',
          correoInstitucional: 'ktorresm@soy.sena.edu.co',
          alternativaEtapaProductiva: 'Pasantía',
          fechaRegistroSofiaPlus: '2026-06-02',
        },
        instructorSeguimiento: {
          nombre: 'Diana Marcela López Ortiz',
          contactoTelefonico: '3112223344',
          correoInstitucional: 'dlopez@sena.edu.co',
        },
        enteCoformador: {
          nombreEmpresa: 'Contadores Asociados del Norte Ltda.',
          direccion: 'Av. 19 # 104-62, Bogotá',
          nit: '830456123-1',
          correoElectronico: 'info@contadoresnorte.com',
          nombreJefeInmediato: 'Ricardo Salcedo Vanegas',
          cargo: 'Contador senior',
          contactoTelefonico: '3157778899',
          nombreOtroContacto: 'Ana Bibiana Rey (RRHH)',
          telefonoInstitucional: '(601) 622 3344',
        },
        discapacidad: { aplica: false, nombreAsiste: '', tipoAsistencia: '', contactoTelefonico: '' },
      },
      momento1: {
        completado: false,
        fechaInicio: '', fechaFin: '', fechaAfiliacionArl: '', numeroPolizaArl: '',
        horario: '', enlaceGrabacion: '',
        competenciasDesarrollar: '', resultadosAprendizaje: '', actividadesDesarrollar: '',
        evidenciasAprendizaje: '', observacionesAdicionales: '',
        firmaAprendiz: false, firmaInstructor: false, firmaEnteCoformador: false,
        ciudad: '', fechaDiligenciamiento: '', modalidadDiligenciamiento: 'VIRTUAL',
      },
      momento2: [],
      momento3: {
        completado: false,
        fechaInicio: '', fechaFin: '', numeroVisitas: 0,
        modalidad: 'VIRTUAL', enlaceGrabacion: '',
        factoresTecnicos: nuevosFactores(FACTORES_TECNICOS),
        factoresActitudinales: nuevosFactores(FACTORES_ACTITUDINALES),
        retroEnteProceso: '', retroEnteDesempeno: '',
        retroInstructorProceso: '', retroInstructorDesempeno: '',
        retroAprendizProceso: '', retroAprendizDesempeno: '',
        juicio: null,
        firmaAprendiz: false, firmaInstructor: false, firmaEnteCoformador: false,
        ciudad: '', fechaDiligenciamiento: '',
      },
      anexos: [],
    },
    {
      id: 3,
      info: {
        regional: 'Distrito Capital',
        centroFormacion: 'Centro de Diseño y Metrología',
        nivelFormativo: 'Tecnólogo',
        programaNombre: 'Gestión Logística',
        programaCodigo: '434305',
        numeroFicha: '2741087',
        modalidadFormacion: 'PRESENCIAL',
        estrategiaFormativa: 'Vínculo laboral',
        fechaFinEtapaLectiva: '2025-12-10',
        aprendiz: {
          nombreCompleto: 'Andrea Sofía Molina Cárdenas',
          tipoDocumento: 'CC',
          numeroIdentificacion: '1010678234',
          contactoTelefonico: '3187896541',
          direccion: 'Cra 30 # 45-11, Bogotá',
          correoPersonal: 'andrea.molinac@gmail.com',
          correoInstitucional: 'asmolinac@soy.sena.edu.co',
          alternativaEtapaProductiva: 'Vínculo laboral',
          fechaRegistroSofiaPlus: '2025-12-18',
        },
        instructorSeguimiento: {
          nombre: 'Jorge Andrés Peña Ruiz',
          contactoTelefonico: '3105551234',
          correoInstitucional: 'jpena@sena.edu.co',
        },
        enteCoformador: {
          nombreEmpresa: 'Logística Integral del Centro SAS',
          direccion: 'Autopista Sur # 32-10, Bogotá',
          nit: '901234567-2',
          correoElectronico: 'operaciones@logisticacentro.co',
          nombreJefeInmediato: 'Fabián Rincón Herrera',
          cargo: 'Coordinador de operaciones',
          contactoTelefonico: '3134445566',
          nombreOtroContacto: '',
          telefonoInstitucional: '(601) 400 1122',
        },
        discapacidad: { aplica: false, nombreAsiste: '', tipoAsistencia: '', contactoTelefonico: '' },
      },
      momento1: {
        completado: true,
        fechaInicio: '2025-12-18', fechaFin: '2026-06-18',
        fechaAfiliacionArl: '2025-12-17', numeroPolizaArl: 'ARL-55019-2025',
        horario: 'Diurno · lunes a sábado 7:00am–3:00pm',
        enlaceGrabacion: '',
        competenciasDesarrollar: 'Coordinar procesos de almacenamiento, inventarios y distribución conforme a la planeación logística.',
        resultadosAprendizaje: 'Optimiza rutas de distribución y controla niveles de inventario según indicadores de la organización.',
        actividadesDesarrollar: 'Apoyo en planeación de rutas, control de inventarios, indicadores de gestión logística.',
        evidenciasAprendizaje: 'Informes de indicadores, bitácora de novedades, reportes de inventario.',
        observacionesAdicionales: 'Aprendiz vinculado laboralmente en la misma empresa donde realizó la etapa lectiva.',
        firmaAprendiz: true, firmaInstructor: true, firmaEnteCoformador: true,
        ciudad: 'Bogotá D.C.', fechaDiligenciamiento: '2025-12-16', modalidadDiligenciamiento: 'PRESENCIAL',
      },
      momento2: [
        {
          id: 1, fecha: '2025-12-18', modalidad: 'PRESENCIAL', enlaceGrabacion: '',
          factoresTecnicos: f1.tecnicos, factoresActitudinales: f1.actitudinales,
          observacionesInstructor: 'Excelente adaptación al ritmo operativo del centro logístico.',
          observacionesAprendiz: 'El equipo me ha apoyado bastante en el proceso.',
          observacionesEnteCoformador: 'Cumple con los tiempos y protocolos de seguridad.',
          firmaAprendiz: true, firmaInstructor: true, firmaEnteCoformador: true,
          ciudad: 'Bogotá D.C.', fechaDiligenciamiento: '2026-01-30',
        },
        {
          id: 2, fecha: '2026-01-30', modalidad: 'PRESENCIAL', enlaceGrabacion: '',
          factoresTecnicos: f2.tecnicos, factoresActitudinales: f2.actitudinales,
          observacionesInstructor: 'Debe reforzar el diligenciamiento de la documentación de etapa productiva.',
          observacionesAprendiz: 'Estoy trabajando en mejorar los reportes semanales.',
          observacionesEnteCoformador: 'Buen desempeño general, con oportunidades en documentación.',
          firmaAprendiz: true, firmaInstructor: true, firmaEnteCoformador: true,
          ciudad: 'Bogotá D.C.', fechaDiligenciamiento: '2026-03-15',
        },
      ],
      momento3: {
        completado: true,
        fechaInicio: '2025-12-18', fechaFin: '2026-06-18', numeroVisitas: 4,
        modalidad: 'PRESENCIAL', enlaceGrabacion: '',
        factoresTecnicos: f1.tecnicos, factoresActitudinales: f1.actitudinales,
        retroEnteProceso: 'Proceso de formación sobresaliente, con gran sentido de responsabilidad.',
        retroEnteDesempeno: 'Domina las competencias técnicas del programa y las aplica con criterio propio.',
        retroInstructorProceso: 'Aprendiz autónoma, cumplió todos los compromisos de seguimiento.',
        retroInstructorDesempeno: 'Buen manejo de indicadores logísticos y trabajo en equipo.',
        retroAprendizProceso: 'El acompañamiento del instructor fue oportuno durante todo el proceso.',
        retroAprendizDesempeno: 'Sí siento que apliqué lo aprendido en el SENA en el día a día.',
        juicio: 'APROBADO',
        firmaAprendiz: true, firmaInstructor: true, firmaEnteCoformador: true,
        ciudad: 'Bogotá D.C.', fechaDiligenciamiento: '2026-06-19',
      },
      anexos: [],
    },
  ]
}
